### PR TITLE
we add frontend (again)

### PR DESCRIPTION
**Pull request by CodeDiego15**
like that bro?

### CODE REVIEW

**Comment by AisDisappeared** [comment]
Hi bro, it has all functionalities i think... ya? Do u dockerized react app too?

**Comment by CodeDiego15** [comment]
Hi bro, no, I don't know how to use docker, sorry. You could try the react app and see if it has what you are looking for

**Comment by AisDisappeared** [comment]
Hi brother, thank you for your pr … i think it doesn’t work if we don’t
dockerize the react frontend side

**Comment by CodeDiego15** [comment]
Ok, I have to create a container, right?

**Comment by CodeDiego15** [comment]
Hello bro, I'm sorry but I won't be able to continue with the project, I'm involved with mine and my work is too long. It was a pleasure meeting you and working with you, I hope we work together on another occasion.

**Comment by AisDisappeared** [comment]
Hi bro, no problem you are my brother and i will be happy to work with you

**Pull request closed without merging**
