### PR TITLE
we add the frontend

### PR DESCRIPTION
**Pull request by CodeDiego15**
eh added the frontend with react and tailwind, the functionality of deleting task and editing task is missing, an apology for not having done the missing functionalities, I will be trying, eh added the functionality of adding task.
Captura de Pantalla 2024-08-23 a la(s) 2 23 36 a  m

### CODE REVIEW

**Comment by CodeDiego15** [comment]
If you want to add or remove anything from the frontend, you can let me know.

**Comment by AisDisappeared** [comment]
> If you want to add or remove anything from the frontend, you can let me know.

Hi bro, Good job! i want all functionalities that i implemented in my Api such as task deletion , task updating , list of tasks and task details! let's go for that

**Comment by CodeDiego15** [comment]
Thank you so much! I'll be working on it tomorrow.

**Comment by AisDisappeared** [comment]
> Thank you so much! I'll be working on it tomorrow.
> 
> 

So i'll check it tomorrow for merging

**Comment by CodeDiego15** [comment]
Alright.

**Comment by CodeDiego15** [comment]
Hey bro, how are you? Can you allow me to make some changes to the backend if necessary?

**Comment by AisDisappeared** [comment]
> Hey bro, how are you? Can you allow me to make some changes to the backend if necessary?

Hi bro, thanks! What changes bro?

**Comment by CodeDiego15** [comment]
To fix some issues and improve the backend, I have made some adjustments and checks. Here are the changes and recommendations for the backend


Fix Method in taskUpdate: Changed the method in the taskUpdate view from POST to PUT to align with the common practice of using PUT for full updates.  `@api_view(['PUT'])
def taskUpdate(request, pk):
    task = Task.objects.get(id=pk)
    serializer = TaskSerializer(instance=task, data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data)
    return Response(serializer.errors, status=400)` Fix to URL Pattern for taskDelete: Make sure the URL pattern for taskDelete matches the URL you are using on the frontend. I used <int:pk> instead of <str:pk> to be consistent with numeric IDs. `path('task-delete/<int:pk>/', taskDelete, name="task-delete")` Exception Handling: Added exception handling to taskDelete to handle cases where the task does not exist and return an appropriate error message. `@api_view(['DELETE'])
def taskDelete(request, pk):
    try:
        task = Task.objects.get(id=pk)
        task.delete()
        return Response("Task deleted successfully.")
    except Task.DoesNotExist:
        return Response("Task not found.", status=404)
`

**Comment by CodeDiego15** [comment]
If it doesn't seem right to you, I can leave it as before.

**Comment by CodeDiego15** [comment]
https://github.com/user-attachments/assets/6ddb9d28-40dc-47c1-82ed-65c606751855

I didn't understand the details very well but here it is.

**Comment by CodeDiego15** [comment]
You're welcome brother!

**Comment by AisDisappeared** [comment]
Hey bro, thanks for all, happy to work with you i am dockerize the frontend
into the drf network

**Comment by CodeDiego15** [comment]
You're welcome bro, I'm still happy to work with you.

**Comment by AisDisappeared** [comment]
Thanks me too, bro i had some issues with dockerization of react app and i
had to use git reset … can you pull request again? And dockerize the react
in Dockerfile and docker compose files?

**Comment by CodeDiego15** [comment]
Sorry for not answering, okay, give me a moment, I just woke up.

**Pull request merged**
